// Code generated by Fern. DO NOT EDIT.

package client

import (
	batch "github.com/flagright/flagright-go/batch"
	businessuserevents "github.com/flagright/flagright-go/businessuserevents"
	businessusers "github.com/flagright/flagright-go/businessusers"
	consumeruserevents "github.com/flagright/flagright-go/consumeruserevents"
	consumerusers "github.com/flagright/flagright-go/consumerusers"
	core "github.com/flagright/flagright-go/core"
	internal "github.com/flagright/flagright-go/internal"
	option "github.com/flagright/flagright-go/option"
	transactionevents "github.com/flagright/flagright-go/transactionevents"
	transactions "github.com/flagright/flagright-go/transactions"
)

type Client struct {
	Transactions       *transactions.Client
	Batch              *batch.Client
	TransactionEvents  *transactionevents.Client
	ConsumerUsers      *consumerusers.Client
	BusinessUsers      *businessusers.Client
	ConsumerUserEvents *consumeruserevents.Client
	BusinessUserEvents *businessuserevents.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Transactions:       transactions.NewClient(options),
		Batch:              batch.NewClient(options),
		TransactionEvents:  transactionevents.NewClient(options),
		ConsumerUsers:      consumerusers.NewClient(options),
		BusinessUsers:      businessusers.NewClient(options),
		ConsumerUserEvents: consumeruserevents.NewClient(options),
		BusinessUserEvents: businessuserevents.NewClient(options),
		options:            options,
		baseURL:            options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
