// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	businessUsersCreateRequestFieldLockCraRiskLevel = big.NewInt(1 << 0)
	businessUsersCreateRequestFieldLockKycRiskLevel = big.NewInt(1 << 1)
	businessUsersCreateRequestFieldValidateUserId   = big.NewInt(1 << 2)
)

type BusinessUsersCreateRequest struct {
	// Boolean string whether Flagright should lock the CRA risk level for the user.
	LockCraRiskLevel *BooleanString `json:"-" url:"lockCraRiskLevel,omitempty"`
	// Boolean string whether Flagright should lock the KYC risk level for the user.
	LockKycRiskLevel *BooleanString `json:"-" url:"lockKycRiskLevel,omitempty"`
	// Boolean string whether Flagright should validate the userId
	ValidateUserId *BooleanString `json:"-" url:"validateUserId,omitempty"`
	Body           *Business      `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BusinessUsersCreateRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetLockCraRiskLevel sets the LockCraRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateRequest) SetLockCraRiskLevel(lockCraRiskLevel *BooleanString) {
	b.LockCraRiskLevel = lockCraRiskLevel
	b.require(businessUsersCreateRequestFieldLockCraRiskLevel)
}

// SetLockKycRiskLevel sets the LockKycRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateRequest) SetLockKycRiskLevel(lockKycRiskLevel *BooleanString) {
	b.LockKycRiskLevel = lockKycRiskLevel
	b.require(businessUsersCreateRequestFieldLockKycRiskLevel)
}

// SetValidateUserId sets the ValidateUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateRequest) SetValidateUserId(validateUserId *BooleanString) {
	b.ValidateUserId = validateUserId
	b.require(businessUsersCreateRequestFieldValidateUserId)
}

func (b *BusinessUsersCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(Business)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.Body = body
	return nil
}

func (b *BusinessUsersCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

// Model for business user risk score response
var (
	businessUserMonitoringResultFieldUserId           = big.NewInt(1 << 0)
	businessUserMonitoringResultFieldRiskScoreDetails = big.NewInt(1 << 1)
	businessUserMonitoringResultFieldHitRules         = big.NewInt(1 << 2)
	businessUserMonitoringResultFieldExecutedRules    = big.NewInt(1 << 3)
)

type BusinessUserMonitoringResult struct {
	// user ID the risk score pertains to
	UserId           string                 `json:"userId" url:"userId"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BusinessUserMonitoringResult) GetUserId() string {
	if b == nil {
		return ""
	}
	return b.UserId
}

func (b *BusinessUserMonitoringResult) GetRiskScoreDetails() *UserRiskScoreDetails {
	if b == nil {
		return nil
	}
	return b.RiskScoreDetails
}

func (b *BusinessUserMonitoringResult) GetHitRules() []*HitRulesDetails {
	if b == nil {
		return nil
	}
	return b.HitRules
}

func (b *BusinessUserMonitoringResult) GetExecutedRules() []*ExecutedRulesResult {
	if b == nil {
		return nil
	}
	return b.ExecutedRules
}

func (b *BusinessUserMonitoringResult) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BusinessUserMonitoringResult) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserMonitoringResult) SetUserId(userId string) {
	b.UserId = userId
	b.require(businessUserMonitoringResultFieldUserId)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserMonitoringResult) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	b.RiskScoreDetails = riskScoreDetails
	b.require(businessUserMonitoringResultFieldRiskScoreDetails)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserMonitoringResult) SetHitRules(hitRules []*HitRulesDetails) {
	b.HitRules = hitRules
	b.require(businessUserMonitoringResultFieldHitRules)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserMonitoringResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	b.ExecutedRules = executedRules
	b.require(businessUserMonitoringResultFieldExecutedRules)
}

func (b *BusinessUserMonitoringResult) UnmarshalJSON(data []byte) error {
	type unmarshaler BusinessUserMonitoringResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BusinessUserMonitoringResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BusinessUserMonitoringResult) MarshalJSON() ([]byte, error) {
	type embed BusinessUserMonitoringResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BusinessUserMonitoringResult) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	businessUsersCreateResponseFieldUserId           = big.NewInt(1 << 0)
	businessUsersCreateResponseFieldRiskScoreDetails = big.NewInt(1 << 1)
	businessUsersCreateResponseFieldHitRules         = big.NewInt(1 << 2)
	businessUsersCreateResponseFieldExecutedRules    = big.NewInt(1 << 3)
	businessUsersCreateResponseFieldMessage          = big.NewInt(1 << 4)
)

type BusinessUsersCreateResponse struct {
	// user ID the risk score pertains to
	UserId           string                 `json:"userId" url:"userId"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	Message          *string                `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BusinessUsersCreateResponse) GetUserId() string {
	if b == nil {
		return ""
	}
	return b.UserId
}

func (b *BusinessUsersCreateResponse) GetRiskScoreDetails() *UserRiskScoreDetails {
	if b == nil {
		return nil
	}
	return b.RiskScoreDetails
}

func (b *BusinessUsersCreateResponse) GetHitRules() []*HitRulesDetails {
	if b == nil {
		return nil
	}
	return b.HitRules
}

func (b *BusinessUsersCreateResponse) GetExecutedRules() []*ExecutedRulesResult {
	if b == nil {
		return nil
	}
	return b.ExecutedRules
}

func (b *BusinessUsersCreateResponse) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BusinessUsersCreateResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BusinessUsersCreateResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateResponse) SetUserId(userId string) {
	b.UserId = userId
	b.require(businessUsersCreateResponseFieldUserId)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateResponse) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	b.RiskScoreDetails = riskScoreDetails
	b.require(businessUsersCreateResponseFieldRiskScoreDetails)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateResponse) SetHitRules(hitRules []*HitRulesDetails) {
	b.HitRules = hitRules
	b.require(businessUsersCreateResponseFieldHitRules)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateResponse) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	b.ExecutedRules = executedRules
	b.require(businessUsersCreateResponseFieldExecutedRules)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUsersCreateResponse) SetMessage(message *string) {
	b.Message = message
	b.require(businessUsersCreateResponseFieldMessage)
}

func (b *BusinessUsersCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BusinessUsersCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BusinessUsersCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BusinessUsersCreateResponse) MarshalJSON() ([]byte, error) {
	type embed BusinessUsersCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BusinessUsersCreateResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
