// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	businessUserEventsCreateRequestFieldAllowUserTypeConversion = big.NewInt(1 << 0)
	businessUserEventsCreateRequestFieldLockKycRiskLevel        = big.NewInt(1 << 1)
	businessUserEventsCreateRequestFieldLockCraRiskLevel        = big.NewInt(1 << 2)
)

type BusinessUserEventsCreateRequest struct {
	// Boolean string whether Flagright should allow a Business user event to be applied to a Consumer user with the same user ID. This will converts a Consumer user to a Business user.
	AllowUserTypeConversion *BooleanString `json:"-" url:"allowUserTypeConversion,omitempty"`
	// Boolean string whether Flagright should lock the KYC risk level for the user.
	LockKycRiskLevel *BooleanString `json:"-" url:"lockKycRiskLevel,omitempty"`
	// Boolean string whether Flagright should lock the CRA risk level for the user.
	LockCraRiskLevel *BooleanString     `json:"-" url:"lockCraRiskLevel,omitempty"`
	Body             *BusinessUserEvent `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (b *BusinessUserEventsCreateRequest) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAllowUserTypeConversion sets the AllowUserTypeConversion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventsCreateRequest) SetAllowUserTypeConversion(allowUserTypeConversion *BooleanString) {
	b.AllowUserTypeConversion = allowUserTypeConversion
	b.require(businessUserEventsCreateRequestFieldAllowUserTypeConversion)
}

// SetLockKycRiskLevel sets the LockKycRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventsCreateRequest) SetLockKycRiskLevel(lockKycRiskLevel *BooleanString) {
	b.LockKycRiskLevel = lockKycRiskLevel
	b.require(businessUserEventsCreateRequestFieldLockKycRiskLevel)
}

// SetLockCraRiskLevel sets the LockCraRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventsCreateRequest) SetLockCraRiskLevel(lockCraRiskLevel *BooleanString) {
	b.LockCraRiskLevel = lockCraRiskLevel
	b.require(businessUserEventsCreateRequestFieldLockCraRiskLevel)
}

func (b *BusinessUserEventsCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(BusinessUserEvent)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.Body = body
	return nil
}

func (b *BusinessUserEventsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

var (
	businessUserEventWithRulesResultFieldTimestamp                     = big.NewInt(1 << 0)
	businessUserEventWithRulesResultFieldUserId                        = big.NewInt(1 << 1)
	businessUserEventWithRulesResultFieldEventId                       = big.NewInt(1 << 2)
	businessUserEventWithRulesResultFieldReason                        = big.NewInt(1 << 3)
	businessUserEventWithRulesResultFieldEventDescription              = big.NewInt(1 << 4)
	businessUserEventWithRulesResultFieldUpdatedBusinessUserAttributes = big.NewInt(1 << 5)
	businessUserEventWithRulesResultFieldExternalLinks                 = big.NewInt(1 << 6)
	businessUserEventWithRulesResultFieldExecutedRules                 = big.NewInt(1 << 7)
	businessUserEventWithRulesResultFieldHitRules                      = big.NewInt(1 << 8)
	businessUserEventWithRulesResultFieldRiskScoreDetails              = big.NewInt(1 << 9)
)

type BusinessUserEventWithRulesResult struct {
	// Timestamp of the event
	Timestamp float64 `json:"timestamp" url:"timestamp"`
	// Transaction ID the event pertains to
	UserId string `json:"userId" url:"userId"`
	// Unique event ID
	EventId *string `json:"eventId,omitempty" url:"eventId,omitempty"`
	// Reason for the event or a state change
	Reason *string `json:"reason,omitempty" url:"reason,omitempty"`
	// Event description
	EventDescription              *string           `json:"eventDescription,omitempty" url:"eventDescription,omitempty"`
	UpdatedBusinessUserAttributes *BusinessOptional `json:"updatedBusinessUserAttributes,omitempty" url:"updatedBusinessUserAttributes,omitempty"`
	// External links related to the business user
	ExternalLinks    []string               `json:"externalLinks,omitempty" url:"externalLinks,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BusinessUserEventWithRulesResult) GetTimestamp() float64 {
	if b == nil {
		return 0
	}
	return b.Timestamp
}

func (b *BusinessUserEventWithRulesResult) GetUserId() string {
	if b == nil {
		return ""
	}
	return b.UserId
}

func (b *BusinessUserEventWithRulesResult) GetEventId() *string {
	if b == nil {
		return nil
	}
	return b.EventId
}

func (b *BusinessUserEventWithRulesResult) GetReason() *string {
	if b == nil {
		return nil
	}
	return b.Reason
}

func (b *BusinessUserEventWithRulesResult) GetEventDescription() *string {
	if b == nil {
		return nil
	}
	return b.EventDescription
}

func (b *BusinessUserEventWithRulesResult) GetUpdatedBusinessUserAttributes() *BusinessOptional {
	if b == nil {
		return nil
	}
	return b.UpdatedBusinessUserAttributes
}

func (b *BusinessUserEventWithRulesResult) GetExternalLinks() []string {
	if b == nil {
		return nil
	}
	return b.ExternalLinks
}

func (b *BusinessUserEventWithRulesResult) GetExecutedRules() []*ExecutedRulesResult {
	if b == nil {
		return nil
	}
	return b.ExecutedRules
}

func (b *BusinessUserEventWithRulesResult) GetHitRules() []*HitRulesDetails {
	if b == nil {
		return nil
	}
	return b.HitRules
}

func (b *BusinessUserEventWithRulesResult) GetRiskScoreDetails() *UserRiskScoreDetails {
	if b == nil {
		return nil
	}
	return b.RiskScoreDetails
}

func (b *BusinessUserEventWithRulesResult) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BusinessUserEventWithRulesResult) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetTimestamp(timestamp float64) {
	b.Timestamp = timestamp
	b.require(businessUserEventWithRulesResultFieldTimestamp)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetUserId(userId string) {
	b.UserId = userId
	b.require(businessUserEventWithRulesResultFieldUserId)
}

// SetEventId sets the EventId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetEventId(eventId *string) {
	b.EventId = eventId
	b.require(businessUserEventWithRulesResultFieldEventId)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetReason(reason *string) {
	b.Reason = reason
	b.require(businessUserEventWithRulesResultFieldReason)
}

// SetEventDescription sets the EventDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetEventDescription(eventDescription *string) {
	b.EventDescription = eventDescription
	b.require(businessUserEventWithRulesResultFieldEventDescription)
}

// SetUpdatedBusinessUserAttributes sets the UpdatedBusinessUserAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetUpdatedBusinessUserAttributes(updatedBusinessUserAttributes *BusinessOptional) {
	b.UpdatedBusinessUserAttributes = updatedBusinessUserAttributes
	b.require(businessUserEventWithRulesResultFieldUpdatedBusinessUserAttributes)
}

// SetExternalLinks sets the ExternalLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetExternalLinks(externalLinks []string) {
	b.ExternalLinks = externalLinks
	b.require(businessUserEventWithRulesResultFieldExternalLinks)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	b.ExecutedRules = executedRules
	b.require(businessUserEventWithRulesResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetHitRules(hitRules []*HitRulesDetails) {
	b.HitRules = hitRules
	b.require(businessUserEventWithRulesResultFieldHitRules)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BusinessUserEventWithRulesResult) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	b.RiskScoreDetails = riskScoreDetails
	b.require(businessUserEventWithRulesResultFieldRiskScoreDetails)
}

func (b *BusinessUserEventWithRulesResult) UnmarshalJSON(data []byte) error {
	type unmarshaler BusinessUserEventWithRulesResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BusinessUserEventWithRulesResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BusinessUserEventWithRulesResult) MarshalJSON() ([]byte, error) {
	type embed BusinessUserEventWithRulesResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BusinessUserEventWithRulesResult) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
