// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
)

type BusinessUserEventsCreateRequest struct {
	// Boolean string whether Flagright should allow a Business user event to be applied to a Consumer user with the same user ID. This will converts a Consumer user to a Business user.
	AllowUserTypeConversion *BooleanString `json:"-" url:"allowUserTypeConversion,omitempty"`
	// Boolean string whether Flagright should lock the KYC risk level for the user.
	LockKycRiskLevel *BooleanString `json:"-" url:"lockKycRiskLevel,omitempty"`
	// Boolean string whether Flagright should lock the CRA risk level for the user.
	LockCraRiskLevel *BooleanString     `json:"-" url:"lockCraRiskLevel,omitempty"`
	Body             *BusinessUserEvent `json:"-" url:"-"`
}

func (b *BusinessUserEventsCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(BusinessUserEvent)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.Body = body
	return nil
}

func (b *BusinessUserEventsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

type BusinessUserEventWithRulesResult struct {
	// Timestamp of the event
	Timestamp float64 `json:"timestamp" url:"timestamp"`
	// Transaction ID the event pertains to
	UserId string `json:"userId" url:"userId"`
	// Unique event ID
	EventId *string `json:"eventId,omitempty" url:"eventId,omitempty"`
	// Reason for the event or a state change
	Reason *string `json:"reason,omitempty" url:"reason,omitempty"`
	// Event description
	EventDescription              *string                `json:"eventDescription,omitempty" url:"eventDescription,omitempty"`
	UpdatedBusinessUserAttributes *BusinessOptional      `json:"updatedBusinessUserAttributes,omitempty" url:"updatedBusinessUserAttributes,omitempty"`
	ExecutedRules                 []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	HitRules                      []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	RiskScoreDetails              *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BusinessUserEventWithRulesResult) GetTimestamp() float64 {
	if b == nil {
		return 0
	}
	return b.Timestamp
}

func (b *BusinessUserEventWithRulesResult) GetUserId() string {
	if b == nil {
		return ""
	}
	return b.UserId
}

func (b *BusinessUserEventWithRulesResult) GetEventId() *string {
	if b == nil {
		return nil
	}
	return b.EventId
}

func (b *BusinessUserEventWithRulesResult) GetReason() *string {
	if b == nil {
		return nil
	}
	return b.Reason
}

func (b *BusinessUserEventWithRulesResult) GetEventDescription() *string {
	if b == nil {
		return nil
	}
	return b.EventDescription
}

func (b *BusinessUserEventWithRulesResult) GetUpdatedBusinessUserAttributes() *BusinessOptional {
	if b == nil {
		return nil
	}
	return b.UpdatedBusinessUserAttributes
}

func (b *BusinessUserEventWithRulesResult) GetExecutedRules() []*ExecutedRulesResult {
	if b == nil {
		return nil
	}
	return b.ExecutedRules
}

func (b *BusinessUserEventWithRulesResult) GetHitRules() []*HitRulesDetails {
	if b == nil {
		return nil
	}
	return b.HitRules
}

func (b *BusinessUserEventWithRulesResult) GetRiskScoreDetails() *UserRiskScoreDetails {
	if b == nil {
		return nil
	}
	return b.RiskScoreDetails
}

func (b *BusinessUserEventWithRulesResult) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BusinessUserEventWithRulesResult) UnmarshalJSON(data []byte) error {
	type unmarshaler BusinessUserEventWithRulesResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BusinessUserEventWithRulesResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BusinessUserEventWithRulesResult) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}
