// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	consumerUserEventsCreateRequestFieldAllowUserTypeConversion = big.NewInt(1 << 0)
	consumerUserEventsCreateRequestFieldLockKycRiskLevel        = big.NewInt(1 << 1)
	consumerUserEventsCreateRequestFieldLockCraRiskLevel        = big.NewInt(1 << 2)
)

type ConsumerUserEventsCreateRequest struct {
	// Boolean string whether Flagright should allow a Consumer user event to be applied to a Business user with the same user ID. This will converts a Business user to a Consumer user.
	AllowUserTypeConversion *BooleanString `json:"-" url:"allowUserTypeConversion,omitempty"`
	// Boolean string whether Flagright should lock the KYC risk level for the user.
	LockKycRiskLevel *BooleanString `json:"-" url:"lockKycRiskLevel,omitempty"`
	// Boolean string whether Flagright should lock the CRA risk level for the user.
	LockCraRiskLevel *BooleanString     `json:"-" url:"lockCraRiskLevel,omitempty"`
	Body             *ConsumerUserEvent `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *ConsumerUserEventsCreateRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAllowUserTypeConversion sets the AllowUserTypeConversion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventsCreateRequest) SetAllowUserTypeConversion(allowUserTypeConversion *BooleanString) {
	c.AllowUserTypeConversion = allowUserTypeConversion
	c.require(consumerUserEventsCreateRequestFieldAllowUserTypeConversion)
}

// SetLockKycRiskLevel sets the LockKycRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventsCreateRequest) SetLockKycRiskLevel(lockKycRiskLevel *BooleanString) {
	c.LockKycRiskLevel = lockKycRiskLevel
	c.require(consumerUserEventsCreateRequestFieldLockKycRiskLevel)
}

// SetLockCraRiskLevel sets the LockCraRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventsCreateRequest) SetLockCraRiskLevel(lockCraRiskLevel *BooleanString) {
	c.LockCraRiskLevel = lockCraRiskLevel
	c.require(consumerUserEventsCreateRequestFieldLockCraRiskLevel)
}

func (c *ConsumerUserEventsCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(ConsumerUserEvent)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *ConsumerUserEventsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

var (
	consumerUserEventWithRulesResultFieldTimestamp                     = big.NewInt(1 << 0)
	consumerUserEventWithRulesResultFieldUserId                        = big.NewInt(1 << 1)
	consumerUserEventWithRulesResultFieldEventId                       = big.NewInt(1 << 2)
	consumerUserEventWithRulesResultFieldReason                        = big.NewInt(1 << 3)
	consumerUserEventWithRulesResultFieldEventDescription              = big.NewInt(1 << 4)
	consumerUserEventWithRulesResultFieldUpdatedConsumerUserAttributes = big.NewInt(1 << 5)
	consumerUserEventWithRulesResultFieldExternalLinks                 = big.NewInt(1 << 6)
	consumerUserEventWithRulesResultFieldExecutedRules                 = big.NewInt(1 << 7)
	consumerUserEventWithRulesResultFieldHitRules                      = big.NewInt(1 << 8)
	consumerUserEventWithRulesResultFieldRiskScoreDetails              = big.NewInt(1 << 9)
)

type ConsumerUserEventWithRulesResult struct {
	// Timestamp of the event
	Timestamp float64 `json:"timestamp" url:"timestamp"`
	// Transaction ID the event pertains to
	UserId string `json:"userId" url:"userId"`
	// Unique event ID
	EventId *string `json:"eventId,omitempty" url:"eventId,omitempty"`
	// Reason for the event or a state change
	Reason *string `json:"reason,omitempty" url:"reason,omitempty"`
	// Event description
	EventDescription              *string       `json:"eventDescription,omitempty" url:"eventDescription,omitempty"`
	UpdatedConsumerUserAttributes *UserOptional `json:"updatedConsumerUserAttributes,omitempty" url:"updatedConsumerUserAttributes,omitempty"`
	// External links related to the consumer user
	ExternalLinks    []string               `json:"externalLinks,omitempty" url:"externalLinks,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConsumerUserEventWithRulesResult) GetTimestamp() float64 {
	if c == nil {
		return 0
	}
	return c.Timestamp
}

func (c *ConsumerUserEventWithRulesResult) GetUserId() string {
	if c == nil {
		return ""
	}
	return c.UserId
}

func (c *ConsumerUserEventWithRulesResult) GetEventId() *string {
	if c == nil {
		return nil
	}
	return c.EventId
}

func (c *ConsumerUserEventWithRulesResult) GetReason() *string {
	if c == nil {
		return nil
	}
	return c.Reason
}

func (c *ConsumerUserEventWithRulesResult) GetEventDescription() *string {
	if c == nil {
		return nil
	}
	return c.EventDescription
}

func (c *ConsumerUserEventWithRulesResult) GetUpdatedConsumerUserAttributes() *UserOptional {
	if c == nil {
		return nil
	}
	return c.UpdatedConsumerUserAttributes
}

func (c *ConsumerUserEventWithRulesResult) GetExternalLinks() []string {
	if c == nil {
		return nil
	}
	return c.ExternalLinks
}

func (c *ConsumerUserEventWithRulesResult) GetExecutedRules() []*ExecutedRulesResult {
	if c == nil {
		return nil
	}
	return c.ExecutedRules
}

func (c *ConsumerUserEventWithRulesResult) GetHitRules() []*HitRulesDetails {
	if c == nil {
		return nil
	}
	return c.HitRules
}

func (c *ConsumerUserEventWithRulesResult) GetRiskScoreDetails() *UserRiskScoreDetails {
	if c == nil {
		return nil
	}
	return c.RiskScoreDetails
}

func (c *ConsumerUserEventWithRulesResult) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConsumerUserEventWithRulesResult) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetTimestamp(timestamp float64) {
	c.Timestamp = timestamp
	c.require(consumerUserEventWithRulesResultFieldTimestamp)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetUserId(userId string) {
	c.UserId = userId
	c.require(consumerUserEventWithRulesResultFieldUserId)
}

// SetEventId sets the EventId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetEventId(eventId *string) {
	c.EventId = eventId
	c.require(consumerUserEventWithRulesResultFieldEventId)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetReason(reason *string) {
	c.Reason = reason
	c.require(consumerUserEventWithRulesResultFieldReason)
}

// SetEventDescription sets the EventDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetEventDescription(eventDescription *string) {
	c.EventDescription = eventDescription
	c.require(consumerUserEventWithRulesResultFieldEventDescription)
}

// SetUpdatedConsumerUserAttributes sets the UpdatedConsumerUserAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetUpdatedConsumerUserAttributes(updatedConsumerUserAttributes *UserOptional) {
	c.UpdatedConsumerUserAttributes = updatedConsumerUserAttributes
	c.require(consumerUserEventWithRulesResultFieldUpdatedConsumerUserAttributes)
}

// SetExternalLinks sets the ExternalLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetExternalLinks(externalLinks []string) {
	c.ExternalLinks = externalLinks
	c.require(consumerUserEventWithRulesResultFieldExternalLinks)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	c.ExecutedRules = executedRules
	c.require(consumerUserEventWithRulesResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetHitRules(hitRules []*HitRulesDetails) {
	c.HitRules = hitRules
	c.require(consumerUserEventWithRulesResultFieldHitRules)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserEventWithRulesResult) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	c.RiskScoreDetails = riskScoreDetails
	c.require(consumerUserEventWithRulesResultFieldRiskScoreDetails)
}

func (c *ConsumerUserEventWithRulesResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ConsumerUserEventWithRulesResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConsumerUserEventWithRulesResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConsumerUserEventWithRulesResult) MarshalJSON() ([]byte, error) {
	type embed ConsumerUserEventWithRulesResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConsumerUserEventWithRulesResult) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
