// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	consumerUsersCreateRequestFieldLockCraRiskLevel = big.NewInt(1 << 0)
	consumerUsersCreateRequestFieldLockKycRiskLevel = big.NewInt(1 << 1)
	consumerUsersCreateRequestFieldValidateUserId   = big.NewInt(1 << 2)
)

type ConsumerUsersCreateRequest struct {
	// Boolean string whether Flagright should lock the CRA risk level for the user.
	LockCraRiskLevel *BooleanString `json:"-" url:"lockCraRiskLevel,omitempty"`
	// Boolean string whether Flagright should lock the KYC risk level for the user.
	LockKycRiskLevel *BooleanString `json:"-" url:"lockKycRiskLevel,omitempty"`
	// Boolean string whether Flagright should validate the userId
	ValidateUserId *BooleanString `json:"-" url:"validateUserId,omitempty"`
	Body           *User          `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *ConsumerUsersCreateRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetLockCraRiskLevel sets the LockCraRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateRequest) SetLockCraRiskLevel(lockCraRiskLevel *BooleanString) {
	c.LockCraRiskLevel = lockCraRiskLevel
	c.require(consumerUsersCreateRequestFieldLockCraRiskLevel)
}

// SetLockKycRiskLevel sets the LockKycRiskLevel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateRequest) SetLockKycRiskLevel(lockKycRiskLevel *BooleanString) {
	c.LockKycRiskLevel = lockKycRiskLevel
	c.require(consumerUsersCreateRequestFieldLockKycRiskLevel)
}

// SetValidateUserId sets the ValidateUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateRequest) SetValidateUserId(validateUserId *BooleanString) {
	c.ValidateUserId = validateUserId
	c.require(consumerUsersCreateRequestFieldValidateUserId)
}

func (c *ConsumerUsersCreateRequest) UnmarshalJSON(data []byte) error {
	body := new(User)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.Body = body
	return nil
}

func (c *ConsumerUsersCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

// Model for consumer user risk score response
var (
	consumerUserMonitoringResultFieldUserId           = big.NewInt(1 << 0)
	consumerUserMonitoringResultFieldRiskScoreDetails = big.NewInt(1 << 1)
	consumerUserMonitoringResultFieldHitRules         = big.NewInt(1 << 2)
	consumerUserMonitoringResultFieldExecutedRules    = big.NewInt(1 << 3)
)

type ConsumerUserMonitoringResult struct {
	// user ID the risk score pertains to
	UserId           string                 `json:"userId" url:"userId"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConsumerUserMonitoringResult) GetUserId() string {
	if c == nil {
		return ""
	}
	return c.UserId
}

func (c *ConsumerUserMonitoringResult) GetRiskScoreDetails() *UserRiskScoreDetails {
	if c == nil {
		return nil
	}
	return c.RiskScoreDetails
}

func (c *ConsumerUserMonitoringResult) GetHitRules() []*HitRulesDetails {
	if c == nil {
		return nil
	}
	return c.HitRules
}

func (c *ConsumerUserMonitoringResult) GetExecutedRules() []*ExecutedRulesResult {
	if c == nil {
		return nil
	}
	return c.ExecutedRules
}

func (c *ConsumerUserMonitoringResult) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConsumerUserMonitoringResult) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserMonitoringResult) SetUserId(userId string) {
	c.UserId = userId
	c.require(consumerUserMonitoringResultFieldUserId)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserMonitoringResult) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	c.RiskScoreDetails = riskScoreDetails
	c.require(consumerUserMonitoringResultFieldRiskScoreDetails)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserMonitoringResult) SetHitRules(hitRules []*HitRulesDetails) {
	c.HitRules = hitRules
	c.require(consumerUserMonitoringResultFieldHitRules)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUserMonitoringResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	c.ExecutedRules = executedRules
	c.require(consumerUserMonitoringResultFieldExecutedRules)
}

func (c *ConsumerUserMonitoringResult) UnmarshalJSON(data []byte) error {
	type unmarshaler ConsumerUserMonitoringResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConsumerUserMonitoringResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConsumerUserMonitoringResult) MarshalJSON() ([]byte, error) {
	type embed ConsumerUserMonitoringResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConsumerUserMonitoringResult) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	consumerUsersCreateResponseFieldUserId           = big.NewInt(1 << 0)
	consumerUsersCreateResponseFieldRiskScoreDetails = big.NewInt(1 << 1)
	consumerUsersCreateResponseFieldHitRules         = big.NewInt(1 << 2)
	consumerUsersCreateResponseFieldExecutedRules    = big.NewInt(1 << 3)
	consumerUsersCreateResponseFieldMessage          = big.NewInt(1 << 4)
)

type ConsumerUsersCreateResponse struct {
	// user ID the risk score pertains to
	UserId           string                 `json:"userId" url:"userId"`
	RiskScoreDetails *UserRiskScoreDetails  `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	HitRules         []*HitRulesDetails     `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	ExecutedRules    []*ExecutedRulesResult `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	Message          *string                `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ConsumerUsersCreateResponse) GetUserId() string {
	if c == nil {
		return ""
	}
	return c.UserId
}

func (c *ConsumerUsersCreateResponse) GetRiskScoreDetails() *UserRiskScoreDetails {
	if c == nil {
		return nil
	}
	return c.RiskScoreDetails
}

func (c *ConsumerUsersCreateResponse) GetHitRules() []*HitRulesDetails {
	if c == nil {
		return nil
	}
	return c.HitRules
}

func (c *ConsumerUsersCreateResponse) GetExecutedRules() []*ExecutedRulesResult {
	if c == nil {
		return nil
	}
	return c.ExecutedRules
}

func (c *ConsumerUsersCreateResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *ConsumerUsersCreateResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ConsumerUsersCreateResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetUserId sets the UserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateResponse) SetUserId(userId string) {
	c.UserId = userId
	c.require(consumerUsersCreateResponseFieldUserId)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateResponse) SetRiskScoreDetails(riskScoreDetails *UserRiskScoreDetails) {
	c.RiskScoreDetails = riskScoreDetails
	c.require(consumerUsersCreateResponseFieldRiskScoreDetails)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateResponse) SetHitRules(hitRules []*HitRulesDetails) {
	c.HitRules = hitRules
	c.require(consumerUsersCreateResponseFieldHitRules)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateResponse) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	c.ExecutedRules = executedRules
	c.require(consumerUsersCreateResponseFieldExecutedRules)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConsumerUsersCreateResponse) SetMessage(message *string) {
	c.Message = message
	c.require(consumerUsersCreateResponseFieldMessage)
}

func (c *ConsumerUsersCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ConsumerUsersCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ConsumerUsersCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ConsumerUsersCreateResponse) MarshalJSON() ([]byte, error) {
	type embed ConsumerUsersCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ConsumerUsersCreateResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}
