// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersConsumerUsersCreateRequest(t *testing.T) {
	t.Run("SetLockCraRiskLevel", func(t *testing.T) {
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueLockCraRiskLevel *BooleanString
		obj.SetLockCraRiskLevel(fernTestValueLockCraRiskLevel)
		assert.Equal(t, fernTestValueLockCraRiskLevel, obj.LockCraRiskLevel)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLockKycRiskLevel", func(t *testing.T) {
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueLockKycRiskLevel *BooleanString
		obj.SetLockKycRiskLevel(fernTestValueLockKycRiskLevel)
		assert.Equal(t, fernTestValueLockKycRiskLevel, obj.LockKycRiskLevel)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValidateUserId", func(t *testing.T) {
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueValidateUserId *BooleanString
		obj.SetValidateUserId(fernTestValueValidateUserId)
		assert.Equal(t, fernTestValueValidateUserId, obj.ValidateUserId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitConsumerUsersCreateRequest(t *testing.T) {
	t.Run("SetLockCraRiskLevel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueLockCraRiskLevel *BooleanString

		// Act
		obj.SetLockCraRiskLevel(fernTestValueLockCraRiskLevel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLockKycRiskLevel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueLockKycRiskLevel *BooleanString

		// Act
		obj.SetLockKycRiskLevel(fernTestValueLockKycRiskLevel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValidateUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateRequest{}
		var fernTestValueValidateUserId *BooleanString

		// Act
		obj.SetValidateUserId(fernTestValueValidateUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersConsumerUserMonitoringResult(t *testing.T) {
	t.Run("SetUserId", func(t *testing.T) {
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRiskScoreDetails", func(t *testing.T) {
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueRiskScoreDetails *UserRiskScoreDetails
		obj.SetRiskScoreDetails(fernTestValueRiskScoreDetails)
		assert.Equal(t, fernTestValueRiskScoreDetails, obj.RiskScoreDetails)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHitRules", func(t *testing.T) {
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueHitRules []*HitRulesDetails
		obj.SetHitRules(fernTestValueHitRules)
		assert.Equal(t, fernTestValueHitRules, obj.HitRules)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExecutedRules", func(t *testing.T) {
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueExecutedRules []*ExecutedRulesResult
		obj.SetExecutedRules(fernTestValueExecutedRules)
		assert.Equal(t, fernTestValueExecutedRules, obj.ExecutedRules)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersConsumerUserMonitoringResult(t *testing.T) {
	t.Run("GetUserId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var expected string
		obj.UserId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserId(), "getter should return the property value")
	})

	t.Run("GetUserId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserId() // Should return zero value
	})

	t.Run("GetRiskScoreDetails", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var expected *UserRiskScoreDetails
		obj.RiskScoreDetails = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRiskScoreDetails(), "getter should return the property value")
	})

	t.Run("GetRiskScoreDetails_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		obj.RiskScoreDetails = nil

		// Act & Assert
		assert.Nil(t, obj.GetRiskScoreDetails(), "getter should return nil when property is nil")
	})

	t.Run("GetRiskScoreDetails_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRiskScoreDetails() // Should return zero value
	})

	t.Run("GetHitRules", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var expected []*HitRulesDetails
		obj.HitRules = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHitRules(), "getter should return the property value")
	})

	t.Run("GetHitRules_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		obj.HitRules = nil

		// Act & Assert
		assert.Nil(t, obj.GetHitRules(), "getter should return nil when property is nil")
	})

	t.Run("GetHitRules_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHitRules() // Should return zero value
	})

	t.Run("GetExecutedRules", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var expected []*ExecutedRulesResult
		obj.ExecutedRules = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExecutedRules(), "getter should return the property value")
	})

	t.Run("GetExecutedRules_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		obj.ExecutedRules = nil

		// Act & Assert
		assert.Nil(t, obj.GetExecutedRules(), "getter should return nil when property is nil")
	})

	t.Run("GetExecutedRules_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExecutedRules() // Should return zero value
	})

}

func TestSettersMarkExplicitConsumerUserMonitoringResult(t *testing.T) {
	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRiskScoreDetails_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueRiskScoreDetails *UserRiskScoreDetails

		// Act
		obj.SetRiskScoreDetails(fernTestValueRiskScoreDetails)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHitRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueHitRules []*HitRulesDetails

		// Act
		obj.SetHitRules(fernTestValueHitRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExecutedRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}
		var fernTestValueExecutedRules []*ExecutedRulesResult

		// Act
		obj.SetExecutedRules(fernTestValueExecutedRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersConsumerUsersCreateResponse(t *testing.T) {
	t.Run("SetUserId", func(t *testing.T) {
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueUserId string
		obj.SetUserId(fernTestValueUserId)
		assert.Equal(t, fernTestValueUserId, obj.UserId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRiskScoreDetails", func(t *testing.T) {
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueRiskScoreDetails *UserRiskScoreDetails
		obj.SetRiskScoreDetails(fernTestValueRiskScoreDetails)
		assert.Equal(t, fernTestValueRiskScoreDetails, obj.RiskScoreDetails)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHitRules", func(t *testing.T) {
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueHitRules []*HitRulesDetails
		obj.SetHitRules(fernTestValueHitRules)
		assert.Equal(t, fernTestValueHitRules, obj.HitRules)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExecutedRules", func(t *testing.T) {
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueExecutedRules []*ExecutedRulesResult
		obj.SetExecutedRules(fernTestValueExecutedRules)
		assert.Equal(t, fernTestValueExecutedRules, obj.ExecutedRules)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMessage", func(t *testing.T) {
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueMessage *string
		obj.SetMessage(fernTestValueMessage)
		assert.Equal(t, fernTestValueMessage, obj.Message)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersConsumerUsersCreateResponse(t *testing.T) {
	t.Run("GetUserId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var expected string
		obj.UserId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUserId(), "getter should return the property value")
	})

	t.Run("GetUserId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUserId() // Should return zero value
	})

	t.Run("GetRiskScoreDetails", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var expected *UserRiskScoreDetails
		obj.RiskScoreDetails = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRiskScoreDetails(), "getter should return the property value")
	})

	t.Run("GetRiskScoreDetails_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		obj.RiskScoreDetails = nil

		// Act & Assert
		assert.Nil(t, obj.GetRiskScoreDetails(), "getter should return nil when property is nil")
	})

	t.Run("GetRiskScoreDetails_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRiskScoreDetails() // Should return zero value
	})

	t.Run("GetHitRules", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var expected []*HitRulesDetails
		obj.HitRules = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHitRules(), "getter should return the property value")
	})

	t.Run("GetHitRules_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		obj.HitRules = nil

		// Act & Assert
		assert.Nil(t, obj.GetHitRules(), "getter should return nil when property is nil")
	})

	t.Run("GetHitRules_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHitRules() // Should return zero value
	})

	t.Run("GetExecutedRules", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var expected []*ExecutedRulesResult
		obj.ExecutedRules = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetExecutedRules(), "getter should return the property value")
	})

	t.Run("GetExecutedRules_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		obj.ExecutedRules = nil

		// Act & Assert
		assert.Nil(t, obj.GetExecutedRules(), "getter should return nil when property is nil")
	})

	t.Run("GetExecutedRules_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetExecutedRules() // Should return zero value
	})

	t.Run("GetMessage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var expected *string
		obj.Message = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMessage(), "getter should return the property value")
	})

	t.Run("GetMessage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		obj.Message = nil

		// Act & Assert
		assert.Nil(t, obj.GetMessage(), "getter should return nil when property is nil")
	})

	t.Run("GetMessage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMessage() // Should return zero value
	})

}

func TestSettersMarkExplicitConsumerUsersCreateResponse(t *testing.T) {
	t.Run("SetUserId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueUserId string

		// Act
		obj.SetUserId(fernTestValueUserId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRiskScoreDetails_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueRiskScoreDetails *UserRiskScoreDetails

		// Act
		obj.SetRiskScoreDetails(fernTestValueRiskScoreDetails)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHitRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueHitRules []*HitRulesDetails

		// Act
		obj.SetHitRules(fernTestValueHitRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExecutedRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueExecutedRules []*ExecutedRulesResult

		// Act
		obj.SetExecutedRules(fernTestValueExecutedRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMessage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}
		var fernTestValueMessage *string

		// Act
		obj.SetMessage(fernTestValueMessage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingConsumerUserMonitoringResult(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUserMonitoringResult{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ConsumerUserMonitoringResult
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ConsumerUserMonitoringResult
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ConsumerUserMonitoringResult
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingConsumerUsersCreateResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConsumerUsersCreateResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ConsumerUsersCreateResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ConsumerUsersCreateResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ConsumerUsersCreateResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringConsumerUserMonitoringResult(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ConsumerUserMonitoringResult{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringConsumerUsersCreateResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ConsumerUsersCreateResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesConsumerUserMonitoringResult(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ConsumerUserMonitoringResult{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUserMonitoringResult
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesConsumerUsersCreateResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ConsumerUsersCreateResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ConsumerUsersCreateResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
