// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	core "github.com/flagright/flagright-go/core"
)

// Bad Request
type BadRequestError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Conflict
type ConflictError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (c *ConflictError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	c.StatusCode = 409
	c.Body = body
	return nil
}

func (c *ConflictError) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.Body)
}

func (c *ConflictError) Unwrap() error {
	return c.APIError
}

// Too Many Requests
type TooManyRequestsError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (t *TooManyRequestsError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.StatusCode = 429
	t.Body = body
	return nil
}

func (t *TooManyRequestsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}

func (t *TooManyRequestsError) Unwrap() error {
	return t.APIError
}

// Unauthorized
type UnauthorizedError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (u *UnauthorizedError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 401
	u.Body = body
	return nil
}

func (u *UnauthorizedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnauthorizedError) Unwrap() error {
	return u.APIError
}
