// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	transactionMonitoringResultFieldTransactionId    = big.NewInt(1 << 0)
	transactionMonitoringResultFieldStatus           = big.NewInt(1 << 1)
	transactionMonitoringResultFieldRiskScoreDetails = big.NewInt(1 << 2)
	transactionMonitoringResultFieldExecutedRules    = big.NewInt(1 << 3)
	transactionMonitoringResultFieldHitRules         = big.NewInt(1 << 4)
)

type TransactionMonitoringResult struct {
	// Transaction ID that the results pertain to
	TransactionId    string                        `json:"transactionId" url:"transactionId"`
	Status           RuleAction                    `json:"status" url:"status"`
	RiskScoreDetails *TransactionRiskScoringResult `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	// Unique transaction identifier
	ExecutedRules []*ExecutedRulesResult `json:"executedRules" url:"executedRules"`
	// Unique transaction identifier
	HitRules []*HitRulesDetails `json:"hitRules" url:"hitRules"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionMonitoringResult) GetTransactionId() string {
	if t == nil {
		return ""
	}
	return t.TransactionId
}

func (t *TransactionMonitoringResult) GetStatus() RuleAction {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *TransactionMonitoringResult) GetRiskScoreDetails() *TransactionRiskScoringResult {
	if t == nil {
		return nil
	}
	return t.RiskScoreDetails
}

func (t *TransactionMonitoringResult) GetExecutedRules() []*ExecutedRulesResult {
	if t == nil {
		return nil
	}
	return t.ExecutedRules
}

func (t *TransactionMonitoringResult) GetHitRules() []*HitRulesDetails {
	if t == nil {
		return nil
	}
	return t.HitRules
}

func (t *TransactionMonitoringResult) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionMonitoringResult) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTransactionId sets the TransactionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionMonitoringResult) SetTransactionId(transactionId string) {
	t.TransactionId = transactionId
	t.require(transactionMonitoringResultFieldTransactionId)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionMonitoringResult) SetStatus(status RuleAction) {
	t.Status = status
	t.require(transactionMonitoringResultFieldStatus)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionMonitoringResult) SetRiskScoreDetails(riskScoreDetails *TransactionRiskScoringResult) {
	t.RiskScoreDetails = riskScoreDetails
	t.require(transactionMonitoringResultFieldRiskScoreDetails)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionMonitoringResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	t.ExecutedRules = executedRules
	t.require(transactionMonitoringResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionMonitoringResult) SetHitRules(hitRules []*HitRulesDetails) {
	t.HitRules = hitRules
	t.require(transactionMonitoringResultFieldHitRules)
}

func (t *TransactionMonitoringResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionMonitoringResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionMonitoringResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionMonitoringResult) MarshalJSON() ([]byte, error) {
	type embed TransactionMonitoringResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionMonitoringResult) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	transactionWithRulesResultFieldType                      = big.NewInt(1 << 0)
	transactionWithRulesResultFieldTransactionId             = big.NewInt(1 << 1)
	transactionWithRulesResultFieldTimestamp                 = big.NewInt(1 << 2)
	transactionWithRulesResultFieldOriginUserId              = big.NewInt(1 << 3)
	transactionWithRulesResultFieldDestinationUserId         = big.NewInt(1 << 4)
	transactionWithRulesResultFieldTransactionState          = big.NewInt(1 << 5)
	transactionWithRulesResultFieldOriginAmountDetails       = big.NewInt(1 << 6)
	transactionWithRulesResultFieldDestinationAmountDetails  = big.NewInt(1 << 7)
	transactionWithRulesResultFieldOriginPaymentDetails      = big.NewInt(1 << 8)
	transactionWithRulesResultFieldDestinationPaymentDetails = big.NewInt(1 << 9)
	transactionWithRulesResultFieldOriginFundsInfo           = big.NewInt(1 << 10)
	transactionWithRulesResultFieldCorporateEntity           = big.NewInt(1 << 11)
	transactionWithRulesResultFieldRelatedTransactionIds     = big.NewInt(1 << 12)
	transactionWithRulesResultFieldProductType               = big.NewInt(1 << 13)
	transactionWithRulesResultFieldPromotionCodeUsed         = big.NewInt(1 << 14)
	transactionWithRulesResultFieldReference                 = big.NewInt(1 << 15)
	transactionWithRulesResultFieldOriginDeviceData          = big.NewInt(1 << 16)
	transactionWithRulesResultFieldDestinationDeviceData     = big.NewInt(1 << 17)
	transactionWithRulesResultFieldMetadata                  = big.NewInt(1 << 18)
	transactionWithRulesResultFieldTags                      = big.NewInt(1 << 19)
	transactionWithRulesResultFieldJurisdiction              = big.NewInt(1 << 20)
	transactionWithRulesResultFieldExternalLinks             = big.NewInt(1 << 21)
	transactionWithRulesResultFieldExecutedRules             = big.NewInt(1 << 22)
	transactionWithRulesResultFieldHitRules                  = big.NewInt(1 << 23)
	transactionWithRulesResultFieldStatus                    = big.NewInt(1 << 24)
	transactionWithRulesResultFieldRiskScoreDetails          = big.NewInt(1 << 25)
)

type TransactionWithRulesResult struct {
	// Type of transaction (ex: DEPOSIT, WITHDRAWAL, TRANSFER, EXTERNAL_PAYMENT, REFUND, OTHER)
	Type string `json:"type" url:"type"`
	// Unique transaction identifier
	TransactionId string `json:"transactionId" url:"transactionId"`
	// Timestamp of when transaction took place
	Timestamp float64 `json:"timestamp" url:"timestamp"`
	// UserId for where the transaction originates from
	OriginUserId *string `json:"originUserId,omitempty" url:"originUserId,omitempty"`
	// UserId for transaction's destination. In other words, where the value is being transferred to.
	DestinationUserId        *string                   `json:"destinationUserId,omitempty" url:"destinationUserId,omitempty"`
	TransactionState         *TransactionState         `json:"transactionState,omitempty" url:"transactionState,omitempty"`
	OriginAmountDetails      *TransactionAmountDetails `json:"originAmountDetails,omitempty" url:"originAmountDetails,omitempty"`
	DestinationAmountDetails *TransactionAmountDetails `json:"destinationAmountDetails,omitempty" url:"destinationAmountDetails,omitempty"`
	// Payment details of the origin. It can be a bank account number, wallet ID, card fingerprint etc.
	OriginPaymentDetails      *TransactionWithRulesResultOriginPaymentDetails      `json:"originPaymentDetails,omitempty" url:"originPaymentDetails,omitempty"`
	DestinationPaymentDetails *TransactionWithRulesResultDestinationPaymentDetails `json:"destinationPaymentDetails,omitempty" url:"destinationPaymentDetails,omitempty"`
	OriginFundsInfo           *OriginFundsInfo                                     `json:"originFundsInfo,omitempty" url:"originFundsInfo,omitempty"`
	CorporateEntity           *CorporateEntityDetails                              `json:"corporateEntity,omitempty" url:"corporateEntity,omitempty"`
	// IDs of transactions related to this transaction. Ex: refund, split bills
	RelatedTransactionIds []string `json:"relatedTransactionIds,omitempty" url:"relatedTransactionIds,omitempty"`
	// Type of produce being used by the consumer (ex wallets, payments etc)
	ProductType *string `json:"productType,omitempty" url:"productType,omitempty"`
	// Whether a promotion code was used or not the transaction
	PromotionCodeUsed *bool `json:"promotionCodeUsed,omitempty" url:"promotionCodeUsed,omitempty"`
	// Reference field for the transaction indicating the purpose of the transaction etc.
	Reference             *string              `json:"reference,omitempty" url:"reference,omitempty"`
	OriginDeviceData      *DeviceData          `json:"originDeviceData,omitempty" url:"originDeviceData,omitempty"`
	DestinationDeviceData *DeviceData          `json:"destinationDeviceData,omitempty" url:"destinationDeviceData,omitempty"`
	Metadata              *TransactionMetadata `json:"metadata,omitempty" url:"metadata,omitempty"`
	// Additional information that can be added via tags
	Tags []*Tag `json:"tags,omitempty" url:"tags,omitempty"`
	// Legal authority or region governing the transaction
	Jurisdiction *string `json:"jurisdiction,omitempty" url:"jurisdiction,omitempty"`
	// External links related to the transaction
	ExternalLinks    []string                      `json:"externalLinks,omitempty" url:"externalLinks,omitempty"`
	ExecutedRules    []*ExecutedRulesResult        `json:"executedRules" url:"executedRules"`
	HitRules         []*HitRulesDetails            `json:"hitRules" url:"hitRules"`
	Status           RuleAction                    `json:"status" url:"status"`
	RiskScoreDetails *TransactionRiskScoringResult `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionWithRulesResult) GetType() string {
	if t == nil {
		return ""
	}
	return t.Type
}

func (t *TransactionWithRulesResult) GetTransactionId() string {
	if t == nil {
		return ""
	}
	return t.TransactionId
}

func (t *TransactionWithRulesResult) GetTimestamp() float64 {
	if t == nil {
		return 0
	}
	return t.Timestamp
}

func (t *TransactionWithRulesResult) GetOriginUserId() *string {
	if t == nil {
		return nil
	}
	return t.OriginUserId
}

func (t *TransactionWithRulesResult) GetDestinationUserId() *string {
	if t == nil {
		return nil
	}
	return t.DestinationUserId
}

func (t *TransactionWithRulesResult) GetTransactionState() *TransactionState {
	if t == nil {
		return nil
	}
	return t.TransactionState
}

func (t *TransactionWithRulesResult) GetOriginAmountDetails() *TransactionAmountDetails {
	if t == nil {
		return nil
	}
	return t.OriginAmountDetails
}

func (t *TransactionWithRulesResult) GetDestinationAmountDetails() *TransactionAmountDetails {
	if t == nil {
		return nil
	}
	return t.DestinationAmountDetails
}

func (t *TransactionWithRulesResult) GetOriginPaymentDetails() *TransactionWithRulesResultOriginPaymentDetails {
	if t == nil {
		return nil
	}
	return t.OriginPaymentDetails
}

func (t *TransactionWithRulesResult) GetDestinationPaymentDetails() *TransactionWithRulesResultDestinationPaymentDetails {
	if t == nil {
		return nil
	}
	return t.DestinationPaymentDetails
}

func (t *TransactionWithRulesResult) GetOriginFundsInfo() *OriginFundsInfo {
	if t == nil {
		return nil
	}
	return t.OriginFundsInfo
}

func (t *TransactionWithRulesResult) GetCorporateEntity() *CorporateEntityDetails {
	if t == nil {
		return nil
	}
	return t.CorporateEntity
}

func (t *TransactionWithRulesResult) GetRelatedTransactionIds() []string {
	if t == nil {
		return nil
	}
	return t.RelatedTransactionIds
}

func (t *TransactionWithRulesResult) GetProductType() *string {
	if t == nil {
		return nil
	}
	return t.ProductType
}

func (t *TransactionWithRulesResult) GetPromotionCodeUsed() *bool {
	if t == nil {
		return nil
	}
	return t.PromotionCodeUsed
}

func (t *TransactionWithRulesResult) GetReference() *string {
	if t == nil {
		return nil
	}
	return t.Reference
}

func (t *TransactionWithRulesResult) GetOriginDeviceData() *DeviceData {
	if t == nil {
		return nil
	}
	return t.OriginDeviceData
}

func (t *TransactionWithRulesResult) GetDestinationDeviceData() *DeviceData {
	if t == nil {
		return nil
	}
	return t.DestinationDeviceData
}

func (t *TransactionWithRulesResult) GetMetadata() *TransactionMetadata {
	if t == nil {
		return nil
	}
	return t.Metadata
}

func (t *TransactionWithRulesResult) GetTags() []*Tag {
	if t == nil {
		return nil
	}
	return t.Tags
}

func (t *TransactionWithRulesResult) GetJurisdiction() *string {
	if t == nil {
		return nil
	}
	return t.Jurisdiction
}

func (t *TransactionWithRulesResult) GetExternalLinks() []string {
	if t == nil {
		return nil
	}
	return t.ExternalLinks
}

func (t *TransactionWithRulesResult) GetExecutedRules() []*ExecutedRulesResult {
	if t == nil {
		return nil
	}
	return t.ExecutedRules
}

func (t *TransactionWithRulesResult) GetHitRules() []*HitRulesDetails {
	if t == nil {
		return nil
	}
	return t.HitRules
}

func (t *TransactionWithRulesResult) GetStatus() RuleAction {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *TransactionWithRulesResult) GetRiskScoreDetails() *TransactionRiskScoringResult {
	if t == nil {
		return nil
	}
	return t.RiskScoreDetails
}

func (t *TransactionWithRulesResult) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionWithRulesResult) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetType(type_ string) {
	t.Type = type_
	t.require(transactionWithRulesResultFieldType)
}

// SetTransactionId sets the TransactionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetTransactionId(transactionId string) {
	t.TransactionId = transactionId
	t.require(transactionWithRulesResultFieldTransactionId)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetTimestamp(timestamp float64) {
	t.Timestamp = timestamp
	t.require(transactionWithRulesResultFieldTimestamp)
}

// SetOriginUserId sets the OriginUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetOriginUserId(originUserId *string) {
	t.OriginUserId = originUserId
	t.require(transactionWithRulesResultFieldOriginUserId)
}

// SetDestinationUserId sets the DestinationUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetDestinationUserId(destinationUserId *string) {
	t.DestinationUserId = destinationUserId
	t.require(transactionWithRulesResultFieldDestinationUserId)
}

// SetTransactionState sets the TransactionState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetTransactionState(transactionState *TransactionState) {
	t.TransactionState = transactionState
	t.require(transactionWithRulesResultFieldTransactionState)
}

// SetOriginAmountDetails sets the OriginAmountDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetOriginAmountDetails(originAmountDetails *TransactionAmountDetails) {
	t.OriginAmountDetails = originAmountDetails
	t.require(transactionWithRulesResultFieldOriginAmountDetails)
}

// SetDestinationAmountDetails sets the DestinationAmountDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetDestinationAmountDetails(destinationAmountDetails *TransactionAmountDetails) {
	t.DestinationAmountDetails = destinationAmountDetails
	t.require(transactionWithRulesResultFieldDestinationAmountDetails)
}

// SetOriginPaymentDetails sets the OriginPaymentDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetOriginPaymentDetails(originPaymentDetails *TransactionWithRulesResultOriginPaymentDetails) {
	t.OriginPaymentDetails = originPaymentDetails
	t.require(transactionWithRulesResultFieldOriginPaymentDetails)
}

// SetDestinationPaymentDetails sets the DestinationPaymentDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetDestinationPaymentDetails(destinationPaymentDetails *TransactionWithRulesResultDestinationPaymentDetails) {
	t.DestinationPaymentDetails = destinationPaymentDetails
	t.require(transactionWithRulesResultFieldDestinationPaymentDetails)
}

// SetOriginFundsInfo sets the OriginFundsInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetOriginFundsInfo(originFundsInfo *OriginFundsInfo) {
	t.OriginFundsInfo = originFundsInfo
	t.require(transactionWithRulesResultFieldOriginFundsInfo)
}

// SetCorporateEntity sets the CorporateEntity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetCorporateEntity(corporateEntity *CorporateEntityDetails) {
	t.CorporateEntity = corporateEntity
	t.require(transactionWithRulesResultFieldCorporateEntity)
}

// SetRelatedTransactionIds sets the RelatedTransactionIds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetRelatedTransactionIds(relatedTransactionIds []string) {
	t.RelatedTransactionIds = relatedTransactionIds
	t.require(transactionWithRulesResultFieldRelatedTransactionIds)
}

// SetProductType sets the ProductType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetProductType(productType *string) {
	t.ProductType = productType
	t.require(transactionWithRulesResultFieldProductType)
}

// SetPromotionCodeUsed sets the PromotionCodeUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetPromotionCodeUsed(promotionCodeUsed *bool) {
	t.PromotionCodeUsed = promotionCodeUsed
	t.require(transactionWithRulesResultFieldPromotionCodeUsed)
}

// SetReference sets the Reference field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetReference(reference *string) {
	t.Reference = reference
	t.require(transactionWithRulesResultFieldReference)
}

// SetOriginDeviceData sets the OriginDeviceData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetOriginDeviceData(originDeviceData *DeviceData) {
	t.OriginDeviceData = originDeviceData
	t.require(transactionWithRulesResultFieldOriginDeviceData)
}

// SetDestinationDeviceData sets the DestinationDeviceData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetDestinationDeviceData(destinationDeviceData *DeviceData) {
	t.DestinationDeviceData = destinationDeviceData
	t.require(transactionWithRulesResultFieldDestinationDeviceData)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetMetadata(metadata *TransactionMetadata) {
	t.Metadata = metadata
	t.require(transactionWithRulesResultFieldMetadata)
}

// SetTags sets the Tags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetTags(tags []*Tag) {
	t.Tags = tags
	t.require(transactionWithRulesResultFieldTags)
}

// SetJurisdiction sets the Jurisdiction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetJurisdiction(jurisdiction *string) {
	t.Jurisdiction = jurisdiction
	t.require(transactionWithRulesResultFieldJurisdiction)
}

// SetExternalLinks sets the ExternalLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetExternalLinks(externalLinks []string) {
	t.ExternalLinks = externalLinks
	t.require(transactionWithRulesResultFieldExternalLinks)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	t.ExecutedRules = executedRules
	t.require(transactionWithRulesResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetHitRules(hitRules []*HitRulesDetails) {
	t.HitRules = hitRules
	t.require(transactionWithRulesResultFieldHitRules)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetStatus(status RuleAction) {
	t.Status = status
	t.require(transactionWithRulesResultFieldStatus)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionWithRulesResult) SetRiskScoreDetails(riskScoreDetails *TransactionRiskScoringResult) {
	t.RiskScoreDetails = riskScoreDetails
	t.require(transactionWithRulesResultFieldRiskScoreDetails)
}

func (t *TransactionWithRulesResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionWithRulesResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionWithRulesResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionWithRulesResult) MarshalJSON() ([]byte, error) {
	type embed TransactionWithRulesResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionWithRulesResult) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type TransactionWithRulesResultDestinationPaymentDetails struct {
	Method             string
	Card               *CardDetails
	GenericBankAccount *GenericBankAccountDetails
	Iban               *IbanDetails
	Ach                *AchDetails
	Upi                *UpiDetails
	Wallet             *WalletDetails
	Swift              *SwiftDetails
	Mpesa              *MpesaDetails
	Check              *CheckDetails
	Cash               *CashDetails
	Npp                *NppDetails
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetMethod() string {
	if t == nil {
		return ""
	}
	return t.Method
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetCard() *CardDetails {
	if t == nil {
		return nil
	}
	return t.Card
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetGenericBankAccount() *GenericBankAccountDetails {
	if t == nil {
		return nil
	}
	return t.GenericBankAccount
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetIban() *IbanDetails {
	if t == nil {
		return nil
	}
	return t.Iban
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetAch() *AchDetails {
	if t == nil {
		return nil
	}
	return t.Ach
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetUpi() *UpiDetails {
	if t == nil {
		return nil
	}
	return t.Upi
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetWallet() *WalletDetails {
	if t == nil {
		return nil
	}
	return t.Wallet
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetSwift() *SwiftDetails {
	if t == nil {
		return nil
	}
	return t.Swift
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetMpesa() *MpesaDetails {
	if t == nil {
		return nil
	}
	return t.Mpesa
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetCheck() *CheckDetails {
	if t == nil {
		return nil
	}
	return t.Check
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetCash() *CashDetails {
	if t == nil {
		return nil
	}
	return t.Cash
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) GetNpp() *NppDetails {
	if t == nil {
		return nil
	}
	return t.Npp
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Method string `json:"method"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	t.Method = unmarshaler.Method
	if unmarshaler.Method == "" {
		return fmt.Errorf("%T did not include discriminant method", t)
	}
	switch unmarshaler.Method {
	case "CARD":
		value := new(CardDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Card = value
	case "GENERIC_BANK_ACCOUNT":
		value := new(GenericBankAccountDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.GenericBankAccount = value
	case "IBAN":
		value := new(IbanDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Iban = value
	case "ACH":
		value := new(AchDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Ach = value
	case "UPI":
		value := new(UpiDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Upi = value
	case "WALLET":
		value := new(WalletDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Wallet = value
	case "SWIFT":
		value := new(SwiftDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Swift = value
	case "MPESA":
		value := new(MpesaDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Mpesa = value
	case "CHECK":
		value := new(CheckDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Check = value
	case "CASH":
		value := new(CashDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Cash = value
	case "NPP":
		value := new(NppDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Npp = value
	}
	return nil
}

func (t TransactionWithRulesResultDestinationPaymentDetails) MarshalJSON() ([]byte, error) {
	if err := t.validate(); err != nil {
		return nil, err
	}
	if t.Card != nil {
		return internal.MarshalJSONWithExtraProperty(t.Card, "method", "CARD")
	}
	if t.GenericBankAccount != nil {
		return internal.MarshalJSONWithExtraProperty(t.GenericBankAccount, "method", "GENERIC_BANK_ACCOUNT")
	}
	if t.Iban != nil {
		return internal.MarshalJSONWithExtraProperty(t.Iban, "method", "IBAN")
	}
	if t.Ach != nil {
		return internal.MarshalJSONWithExtraProperty(t.Ach, "method", "ACH")
	}
	if t.Upi != nil {
		return internal.MarshalJSONWithExtraProperty(t.Upi, "method", "UPI")
	}
	if t.Wallet != nil {
		return internal.MarshalJSONWithExtraProperty(t.Wallet, "method", "WALLET")
	}
	if t.Swift != nil {
		return internal.MarshalJSONWithExtraProperty(t.Swift, "method", "SWIFT")
	}
	if t.Mpesa != nil {
		return internal.MarshalJSONWithExtraProperty(t.Mpesa, "method", "MPESA")
	}
	if t.Check != nil {
		return internal.MarshalJSONWithExtraProperty(t.Check, "method", "CHECK")
	}
	if t.Cash != nil {
		return internal.MarshalJSONWithExtraProperty(t.Cash, "method", "CASH")
	}
	if t.Npp != nil {
		return internal.MarshalJSONWithExtraProperty(t.Npp, "method", "NPP")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", t)
}

type TransactionWithRulesResultDestinationPaymentDetailsVisitor interface {
	VisitCard(*CardDetails) error
	VisitGenericBankAccount(*GenericBankAccountDetails) error
	VisitIban(*IbanDetails) error
	VisitAch(*AchDetails) error
	VisitUpi(*UpiDetails) error
	VisitWallet(*WalletDetails) error
	VisitSwift(*SwiftDetails) error
	VisitMpesa(*MpesaDetails) error
	VisitCheck(*CheckDetails) error
	VisitCash(*CashDetails) error
	VisitNpp(*NppDetails) error
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) Accept(visitor TransactionWithRulesResultDestinationPaymentDetailsVisitor) error {
	if t.Card != nil {
		return visitor.VisitCard(t.Card)
	}
	if t.GenericBankAccount != nil {
		return visitor.VisitGenericBankAccount(t.GenericBankAccount)
	}
	if t.Iban != nil {
		return visitor.VisitIban(t.Iban)
	}
	if t.Ach != nil {
		return visitor.VisitAch(t.Ach)
	}
	if t.Upi != nil {
		return visitor.VisitUpi(t.Upi)
	}
	if t.Wallet != nil {
		return visitor.VisitWallet(t.Wallet)
	}
	if t.Swift != nil {
		return visitor.VisitSwift(t.Swift)
	}
	if t.Mpesa != nil {
		return visitor.VisitMpesa(t.Mpesa)
	}
	if t.Check != nil {
		return visitor.VisitCheck(t.Check)
	}
	if t.Cash != nil {
		return visitor.VisitCash(t.Cash)
	}
	if t.Npp != nil {
		return visitor.VisitNpp(t.Npp)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", t)
}

func (t *TransactionWithRulesResultDestinationPaymentDetails) validate() error {
	if t == nil {
		return fmt.Errorf("type %T is nil", t)
	}
	var fields []string
	if t.Card != nil {
		fields = append(fields, "CARD")
	}
	if t.GenericBankAccount != nil {
		fields = append(fields, "GENERIC_BANK_ACCOUNT")
	}
	if t.Iban != nil {
		fields = append(fields, "IBAN")
	}
	if t.Ach != nil {
		fields = append(fields, "ACH")
	}
	if t.Upi != nil {
		fields = append(fields, "UPI")
	}
	if t.Wallet != nil {
		fields = append(fields, "WALLET")
	}
	if t.Swift != nil {
		fields = append(fields, "SWIFT")
	}
	if t.Mpesa != nil {
		fields = append(fields, "MPESA")
	}
	if t.Check != nil {
		fields = append(fields, "CHECK")
	}
	if t.Cash != nil {
		fields = append(fields, "CASH")
	}
	if t.Npp != nil {
		fields = append(fields, "NPP")
	}
	if len(fields) == 0 {
		if t.Method != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", t, t.Method)
		}
		return fmt.Errorf("type %T is empty", t)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", t, fields)
	}
	if t.Method != "" {
		field := fields[0]
		if t.Method != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				t,
				t.Method,
				t,
			)
		}
	}
	return nil
}

// Payment details of the origin. It can be a bank account number, wallet ID, card fingerprint etc.
type TransactionWithRulesResultOriginPaymentDetails struct {
	Method             string
	Card               *CardDetails
	GenericBankAccount *GenericBankAccountDetails
	Iban               *IbanDetails
	Ach                *AchDetails
	Swift              *SwiftDetails
	Mpesa              *MpesaDetails
	Upi                *UpiDetails
	Wallet             *WalletDetails
	Check              *CheckDetails
	Cash               *CashDetails
	Npp                *NppDetails
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetMethod() string {
	if t == nil {
		return ""
	}
	return t.Method
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetCard() *CardDetails {
	if t == nil {
		return nil
	}
	return t.Card
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetGenericBankAccount() *GenericBankAccountDetails {
	if t == nil {
		return nil
	}
	return t.GenericBankAccount
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetIban() *IbanDetails {
	if t == nil {
		return nil
	}
	return t.Iban
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetAch() *AchDetails {
	if t == nil {
		return nil
	}
	return t.Ach
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetSwift() *SwiftDetails {
	if t == nil {
		return nil
	}
	return t.Swift
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetMpesa() *MpesaDetails {
	if t == nil {
		return nil
	}
	return t.Mpesa
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetUpi() *UpiDetails {
	if t == nil {
		return nil
	}
	return t.Upi
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetWallet() *WalletDetails {
	if t == nil {
		return nil
	}
	return t.Wallet
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetCheck() *CheckDetails {
	if t == nil {
		return nil
	}
	return t.Check
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetCash() *CashDetails {
	if t == nil {
		return nil
	}
	return t.Cash
}

func (t *TransactionWithRulesResultOriginPaymentDetails) GetNpp() *NppDetails {
	if t == nil {
		return nil
	}
	return t.Npp
}

func (t *TransactionWithRulesResultOriginPaymentDetails) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Method string `json:"method"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	t.Method = unmarshaler.Method
	if unmarshaler.Method == "" {
		return fmt.Errorf("%T did not include discriminant method", t)
	}
	switch unmarshaler.Method {
	case "CARD":
		value := new(CardDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Card = value
	case "GENERIC_BANK_ACCOUNT":
		value := new(GenericBankAccountDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.GenericBankAccount = value
	case "IBAN":
		value := new(IbanDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Iban = value
	case "ACH":
		value := new(AchDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Ach = value
	case "SWIFT":
		value := new(SwiftDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Swift = value
	case "MPESA":
		value := new(MpesaDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Mpesa = value
	case "UPI":
		value := new(UpiDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Upi = value
	case "WALLET":
		value := new(WalletDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Wallet = value
	case "CHECK":
		value := new(CheckDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Check = value
	case "CASH":
		value := new(CashDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Cash = value
	case "NPP":
		value := new(NppDetails)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Npp = value
	}
	return nil
}

func (t TransactionWithRulesResultOriginPaymentDetails) MarshalJSON() ([]byte, error) {
	if err := t.validate(); err != nil {
		return nil, err
	}
	if t.Card != nil {
		return internal.MarshalJSONWithExtraProperty(t.Card, "method", "CARD")
	}
	if t.GenericBankAccount != nil {
		return internal.MarshalJSONWithExtraProperty(t.GenericBankAccount, "method", "GENERIC_BANK_ACCOUNT")
	}
	if t.Iban != nil {
		return internal.MarshalJSONWithExtraProperty(t.Iban, "method", "IBAN")
	}
	if t.Ach != nil {
		return internal.MarshalJSONWithExtraProperty(t.Ach, "method", "ACH")
	}
	if t.Swift != nil {
		return internal.MarshalJSONWithExtraProperty(t.Swift, "method", "SWIFT")
	}
	if t.Mpesa != nil {
		return internal.MarshalJSONWithExtraProperty(t.Mpesa, "method", "MPESA")
	}
	if t.Upi != nil {
		return internal.MarshalJSONWithExtraProperty(t.Upi, "method", "UPI")
	}
	if t.Wallet != nil {
		return internal.MarshalJSONWithExtraProperty(t.Wallet, "method", "WALLET")
	}
	if t.Check != nil {
		return internal.MarshalJSONWithExtraProperty(t.Check, "method", "CHECK")
	}
	if t.Cash != nil {
		return internal.MarshalJSONWithExtraProperty(t.Cash, "method", "CASH")
	}
	if t.Npp != nil {
		return internal.MarshalJSONWithExtraProperty(t.Npp, "method", "NPP")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", t)
}

type TransactionWithRulesResultOriginPaymentDetailsVisitor interface {
	VisitCard(*CardDetails) error
	VisitGenericBankAccount(*GenericBankAccountDetails) error
	VisitIban(*IbanDetails) error
	VisitAch(*AchDetails) error
	VisitSwift(*SwiftDetails) error
	VisitMpesa(*MpesaDetails) error
	VisitUpi(*UpiDetails) error
	VisitWallet(*WalletDetails) error
	VisitCheck(*CheckDetails) error
	VisitCash(*CashDetails) error
	VisitNpp(*NppDetails) error
}

func (t *TransactionWithRulesResultOriginPaymentDetails) Accept(visitor TransactionWithRulesResultOriginPaymentDetailsVisitor) error {
	if t.Card != nil {
		return visitor.VisitCard(t.Card)
	}
	if t.GenericBankAccount != nil {
		return visitor.VisitGenericBankAccount(t.GenericBankAccount)
	}
	if t.Iban != nil {
		return visitor.VisitIban(t.Iban)
	}
	if t.Ach != nil {
		return visitor.VisitAch(t.Ach)
	}
	if t.Swift != nil {
		return visitor.VisitSwift(t.Swift)
	}
	if t.Mpesa != nil {
		return visitor.VisitMpesa(t.Mpesa)
	}
	if t.Upi != nil {
		return visitor.VisitUpi(t.Upi)
	}
	if t.Wallet != nil {
		return visitor.VisitWallet(t.Wallet)
	}
	if t.Check != nil {
		return visitor.VisitCheck(t.Check)
	}
	if t.Cash != nil {
		return visitor.VisitCash(t.Cash)
	}
	if t.Npp != nil {
		return visitor.VisitNpp(t.Npp)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", t)
}

func (t *TransactionWithRulesResultOriginPaymentDetails) validate() error {
	if t == nil {
		return fmt.Errorf("type %T is nil", t)
	}
	var fields []string
	if t.Card != nil {
		fields = append(fields, "CARD")
	}
	if t.GenericBankAccount != nil {
		fields = append(fields, "GENERIC_BANK_ACCOUNT")
	}
	if t.Iban != nil {
		fields = append(fields, "IBAN")
	}
	if t.Ach != nil {
		fields = append(fields, "ACH")
	}
	if t.Swift != nil {
		fields = append(fields, "SWIFT")
	}
	if t.Mpesa != nil {
		fields = append(fields, "MPESA")
	}
	if t.Upi != nil {
		fields = append(fields, "UPI")
	}
	if t.Wallet != nil {
		fields = append(fields, "WALLET")
	}
	if t.Check != nil {
		fields = append(fields, "CHECK")
	}
	if t.Cash != nil {
		fields = append(fields, "CASH")
	}
	if t.Npp != nil {
		fields = append(fields, "NPP")
	}
	if len(fields) == 0 {
		if t.Method != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", t, t.Method)
		}
		return fmt.Errorf("type %T is empty", t)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", t, fields)
	}
	if t.Method != "" {
		field := fields[0]
		if t.Method != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				t,
				t.Method,
				t,
			)
		}
	}
	return nil
}

var (
	transactionsVerifyResponseFieldTransactionId    = big.NewInt(1 << 0)
	transactionsVerifyResponseFieldStatus           = big.NewInt(1 << 1)
	transactionsVerifyResponseFieldRiskScoreDetails = big.NewInt(1 << 2)
	transactionsVerifyResponseFieldExecutedRules    = big.NewInt(1 << 3)
	transactionsVerifyResponseFieldHitRules         = big.NewInt(1 << 4)
	transactionsVerifyResponseFieldMessage          = big.NewInt(1 << 5)
)

type TransactionsVerifyResponse struct {
	// Transaction ID that the results pertain to
	TransactionId    string                        `json:"transactionId" url:"transactionId"`
	Status           RuleAction                    `json:"status" url:"status"`
	RiskScoreDetails *TransactionRiskScoringResult `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	// Unique transaction identifier
	ExecutedRules []*ExecutedRulesResult `json:"executedRules" url:"executedRules"`
	// Unique transaction identifier
	HitRules []*HitRulesDetails `json:"hitRules" url:"hitRules"`
	Message  *string            `json:"message,omitempty" url:"message,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionsVerifyResponse) GetTransactionId() string {
	if t == nil {
		return ""
	}
	return t.TransactionId
}

func (t *TransactionsVerifyResponse) GetStatus() RuleAction {
	if t == nil {
		return ""
	}
	return t.Status
}

func (t *TransactionsVerifyResponse) GetRiskScoreDetails() *TransactionRiskScoringResult {
	if t == nil {
		return nil
	}
	return t.RiskScoreDetails
}

func (t *TransactionsVerifyResponse) GetExecutedRules() []*ExecutedRulesResult {
	if t == nil {
		return nil
	}
	return t.ExecutedRules
}

func (t *TransactionsVerifyResponse) GetHitRules() []*HitRulesDetails {
	if t == nil {
		return nil
	}
	return t.HitRules
}

func (t *TransactionsVerifyResponse) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

func (t *TransactionsVerifyResponse) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionsVerifyResponse) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTransactionId sets the TransactionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetTransactionId(transactionId string) {
	t.TransactionId = transactionId
	t.require(transactionsVerifyResponseFieldTransactionId)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetStatus(status RuleAction) {
	t.Status = status
	t.require(transactionsVerifyResponseFieldStatus)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetRiskScoreDetails(riskScoreDetails *TransactionRiskScoringResult) {
	t.RiskScoreDetails = riskScoreDetails
	t.require(transactionsVerifyResponseFieldRiskScoreDetails)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	t.ExecutedRules = executedRules
	t.require(transactionsVerifyResponseFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetHitRules(hitRules []*HitRulesDetails) {
	t.HitRules = hitRules
	t.require(transactionsVerifyResponseFieldHitRules)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyResponse) SetMessage(message *string) {
	t.Message = message
	t.require(transactionsVerifyResponseFieldMessage)
}

func (t *TransactionsVerifyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionsVerifyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionsVerifyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionsVerifyResponse) MarshalJSON() ([]byte, error) {
	type embed TransactionsVerifyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionsVerifyResponse) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	transactionsVerifyRequestFieldValidateOriginUserId      = big.NewInt(1 << 0)
	transactionsVerifyRequestFieldValidateDestinationUserId = big.NewInt(1 << 1)
)

type TransactionsVerifyRequest struct {
	// Boolean string whether Flagright should validate if provided originUserId exist. True by default
	ValidateOriginUserId *BooleanString `json:"-" url:"validateOriginUserId,omitempty"`
	// Boolean string whether Flagright should validate if provided destinationUserId exist. True by default
	ValidateDestinationUserId *BooleanString `json:"-" url:"validateDestinationUserId,omitempty"`
	Body                      *Transaction   `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TransactionsVerifyRequest) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetValidateOriginUserId sets the ValidateOriginUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyRequest) SetValidateOriginUserId(validateOriginUserId *BooleanString) {
	t.ValidateOriginUserId = validateOriginUserId
	t.require(transactionsVerifyRequestFieldValidateOriginUserId)
}

// SetValidateDestinationUserId sets the ValidateDestinationUserId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionsVerifyRequest) SetValidateDestinationUserId(validateDestinationUserId *BooleanString) {
	t.ValidateDestinationUserId = validateDestinationUserId
	t.require(transactionsVerifyRequestFieldValidateDestinationUserId)
}

func (t *TransactionsVerifyRequest) UnmarshalJSON(data []byte) error {
	body := new(Transaction)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	t.Body = body
	return nil
}

func (t *TransactionsVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.Body)
}
