// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/flagright/flagright-go/internal"
	big "math/big"
)

var (
	transactionEventMonitoringResultFieldEventId          = big.NewInt(1 << 0)
	transactionEventMonitoringResultFieldTransaction      = big.NewInt(1 << 1)
	transactionEventMonitoringResultFieldStatus           = big.NewInt(1 << 2)
	transactionEventMonitoringResultFieldRiskScoreDetails = big.NewInt(1 << 3)
	transactionEventMonitoringResultFieldExecutedRules    = big.NewInt(1 << 4)
	transactionEventMonitoringResultFieldHitRules         = big.NewInt(1 << 5)
)

type TransactionEventMonitoringResult struct {
	EventId          string                        `json:"eventId" url:"eventId"`
	Transaction      *Transaction                  `json:"transaction" url:"transaction"`
	Status           *RuleAction                   `json:"status,omitempty" url:"status,omitempty"`
	RiskScoreDetails *TransactionRiskScoringResult `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`
	// Unique transaction identifier
	ExecutedRules []*ExecutedRulesResult `json:"executedRules" url:"executedRules"`
	// Unique transaction identifier
	HitRules []*HitRulesDetails `json:"hitRules" url:"hitRules"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionEventMonitoringResult) GetEventId() string {
	if t == nil {
		return ""
	}
	return t.EventId
}

func (t *TransactionEventMonitoringResult) GetTransaction() *Transaction {
	if t == nil {
		return nil
	}
	return t.Transaction
}

func (t *TransactionEventMonitoringResult) GetStatus() *RuleAction {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TransactionEventMonitoringResult) GetRiskScoreDetails() *TransactionRiskScoringResult {
	if t == nil {
		return nil
	}
	return t.RiskScoreDetails
}

func (t *TransactionEventMonitoringResult) GetExecutedRules() []*ExecutedRulesResult {
	if t == nil {
		return nil
	}
	return t.ExecutedRules
}

func (t *TransactionEventMonitoringResult) GetHitRules() []*HitRulesDetails {
	if t == nil {
		return nil
	}
	return t.HitRules
}

func (t *TransactionEventMonitoringResult) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionEventMonitoringResult) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetEventId sets the EventId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetEventId(eventId string) {
	t.EventId = eventId
	t.require(transactionEventMonitoringResultFieldEventId)
}

// SetTransaction sets the Transaction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetTransaction(transaction *Transaction) {
	t.Transaction = transaction
	t.require(transactionEventMonitoringResultFieldTransaction)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetStatus(status *RuleAction) {
	t.Status = status
	t.require(transactionEventMonitoringResultFieldStatus)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetRiskScoreDetails(riskScoreDetails *TransactionRiskScoringResult) {
	t.RiskScoreDetails = riskScoreDetails
	t.require(transactionEventMonitoringResultFieldRiskScoreDetails)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	t.ExecutedRules = executedRules
	t.require(transactionEventMonitoringResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventMonitoringResult) SetHitRules(hitRules []*HitRulesDetails) {
	t.HitRules = hitRules
	t.require(transactionEventMonitoringResultFieldHitRules)
}

func (t *TransactionEventMonitoringResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionEventMonitoringResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionEventMonitoringResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionEventMonitoringResult) MarshalJSON() ([]byte, error) {
	type embed TransactionEventMonitoringResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionEventMonitoringResult) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	transactionEventWithRulesResultFieldTransactionState             = big.NewInt(1 << 0)
	transactionEventWithRulesResultFieldTimestamp                    = big.NewInt(1 << 1)
	transactionEventWithRulesResultFieldTransactionId                = big.NewInt(1 << 2)
	transactionEventWithRulesResultFieldEventId                      = big.NewInt(1 << 3)
	transactionEventWithRulesResultFieldReason                       = big.NewInt(1 << 4)
	transactionEventWithRulesResultFieldEventDescription             = big.NewInt(1 << 5)
	transactionEventWithRulesResultFieldUpdatedTransactionAttributes = big.NewInt(1 << 6)
	transactionEventWithRulesResultFieldMetaData                     = big.NewInt(1 << 7)
	transactionEventWithRulesResultFieldExternalLinks                = big.NewInt(1 << 8)
	transactionEventWithRulesResultFieldExecutedRules                = big.NewInt(1 << 9)
	transactionEventWithRulesResultFieldHitRules                     = big.NewInt(1 << 10)
	transactionEventWithRulesResultFieldStatus                       = big.NewInt(1 << 11)
	transactionEventWithRulesResultFieldRiskScoreDetails             = big.NewInt(1 << 12)
)

type TransactionEventWithRulesResult struct {
	TransactionState TransactionState `json:"transactionState" url:"transactionState"`
	// Timestamp of the event
	Timestamp float64 `json:"timestamp" url:"timestamp"`
	// Transaction ID the event pertains to
	TransactionId string `json:"transactionId" url:"transactionId"`
	// Unique event ID
	EventId *string `json:"eventId,omitempty" url:"eventId,omitempty"`
	// Reason for the event or a state change
	Reason *string `json:"reason,omitempty" url:"reason,omitempty"`
	// Event description
	EventDescription             *string               `json:"eventDescription,omitempty" url:"eventDescription,omitempty"`
	UpdatedTransactionAttributes *TransactionUpdatable `json:"updatedTransactionAttributes,omitempty" url:"updatedTransactionAttributes,omitempty"`
	MetaData                     *DeviceData           `json:"metaData,omitempty" url:"metaData,omitempty"`
	// External links related to the transaction
	ExternalLinks    []string                      `json:"externalLinks,omitempty" url:"externalLinks,omitempty"`
	ExecutedRules    []*ExecutedRulesResult        `json:"executedRules,omitempty" url:"executedRules,omitempty"`
	HitRules         []*HitRulesDetails            `json:"hitRules,omitempty" url:"hitRules,omitempty"`
	Status           *RuleAction                   `json:"status,omitempty" url:"status,omitempty"`
	RiskScoreDetails *TransactionRiskScoringResult `json:"riskScoreDetails,omitempty" url:"riskScoreDetails,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionEventWithRulesResult) GetTransactionState() TransactionState {
	if t == nil {
		return ""
	}
	return t.TransactionState
}

func (t *TransactionEventWithRulesResult) GetTimestamp() float64 {
	if t == nil {
		return 0
	}
	return t.Timestamp
}

func (t *TransactionEventWithRulesResult) GetTransactionId() string {
	if t == nil {
		return ""
	}
	return t.TransactionId
}

func (t *TransactionEventWithRulesResult) GetEventId() *string {
	if t == nil {
		return nil
	}
	return t.EventId
}

func (t *TransactionEventWithRulesResult) GetReason() *string {
	if t == nil {
		return nil
	}
	return t.Reason
}

func (t *TransactionEventWithRulesResult) GetEventDescription() *string {
	if t == nil {
		return nil
	}
	return t.EventDescription
}

func (t *TransactionEventWithRulesResult) GetUpdatedTransactionAttributes() *TransactionUpdatable {
	if t == nil {
		return nil
	}
	return t.UpdatedTransactionAttributes
}

func (t *TransactionEventWithRulesResult) GetMetaData() *DeviceData {
	if t == nil {
		return nil
	}
	return t.MetaData
}

func (t *TransactionEventWithRulesResult) GetExternalLinks() []string {
	if t == nil {
		return nil
	}
	return t.ExternalLinks
}

func (t *TransactionEventWithRulesResult) GetExecutedRules() []*ExecutedRulesResult {
	if t == nil {
		return nil
	}
	return t.ExecutedRules
}

func (t *TransactionEventWithRulesResult) GetHitRules() []*HitRulesDetails {
	if t == nil {
		return nil
	}
	return t.HitRules
}

func (t *TransactionEventWithRulesResult) GetStatus() *RuleAction {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TransactionEventWithRulesResult) GetRiskScoreDetails() *TransactionRiskScoringResult {
	if t == nil {
		return nil
	}
	return t.RiskScoreDetails
}

func (t *TransactionEventWithRulesResult) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionEventWithRulesResult) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTransactionState sets the TransactionState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetTransactionState(transactionState TransactionState) {
	t.TransactionState = transactionState
	t.require(transactionEventWithRulesResultFieldTransactionState)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetTimestamp(timestamp float64) {
	t.Timestamp = timestamp
	t.require(transactionEventWithRulesResultFieldTimestamp)
}

// SetTransactionId sets the TransactionId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetTransactionId(transactionId string) {
	t.TransactionId = transactionId
	t.require(transactionEventWithRulesResultFieldTransactionId)
}

// SetEventId sets the EventId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetEventId(eventId *string) {
	t.EventId = eventId
	t.require(transactionEventWithRulesResultFieldEventId)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetReason(reason *string) {
	t.Reason = reason
	t.require(transactionEventWithRulesResultFieldReason)
}

// SetEventDescription sets the EventDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetEventDescription(eventDescription *string) {
	t.EventDescription = eventDescription
	t.require(transactionEventWithRulesResultFieldEventDescription)
}

// SetUpdatedTransactionAttributes sets the UpdatedTransactionAttributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetUpdatedTransactionAttributes(updatedTransactionAttributes *TransactionUpdatable) {
	t.UpdatedTransactionAttributes = updatedTransactionAttributes
	t.require(transactionEventWithRulesResultFieldUpdatedTransactionAttributes)
}

// SetMetaData sets the MetaData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetMetaData(metaData *DeviceData) {
	t.MetaData = metaData
	t.require(transactionEventWithRulesResultFieldMetaData)
}

// SetExternalLinks sets the ExternalLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetExternalLinks(externalLinks []string) {
	t.ExternalLinks = externalLinks
	t.require(transactionEventWithRulesResultFieldExternalLinks)
}

// SetExecutedRules sets the ExecutedRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetExecutedRules(executedRules []*ExecutedRulesResult) {
	t.ExecutedRules = executedRules
	t.require(transactionEventWithRulesResultFieldExecutedRules)
}

// SetHitRules sets the HitRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetHitRules(hitRules []*HitRulesDetails) {
	t.HitRules = hitRules
	t.require(transactionEventWithRulesResultFieldHitRules)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetStatus(status *RuleAction) {
	t.Status = status
	t.require(transactionEventWithRulesResultFieldStatus)
}

// SetRiskScoreDetails sets the RiskScoreDetails field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionEventWithRulesResult) SetRiskScoreDetails(riskScoreDetails *TransactionRiskScoringResult) {
	t.RiskScoreDetails = riskScoreDetails
	t.require(transactionEventWithRulesResultFieldRiskScoreDetails)
}

func (t *TransactionEventWithRulesResult) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionEventWithRulesResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionEventWithRulesResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionEventWithRulesResult) MarshalJSON() ([]byte, error) {
	type embed TransactionEventWithRulesResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionEventWithRulesResult) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
