// Code generated by Fern. DO NOT EDIT.

package batch

import (
	context "context"

	flagrightgo "github.com/flagright/flagright-go"
	core "github.com/flagright/flagright-go/core"
	internal "github.com/flagright/flagright-go/internal"
	option "github.com/flagright/flagright-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) VerifyTransaction(
	ctx context.Context,
	request *flagrightgo.TransactionBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.VerifyTransaction(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTransactions(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetTransactionsRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchTransactionMonitoringResults, error) {
	response, err := c.WithRawResponse.GetTransactions(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateTransactionEvents(
	ctx context.Context,
	request *flagrightgo.TransactionEventBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.CreateTransactionEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetTransactionEvents(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetTransactionEventsRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchTransactionEventMonitoringResults, error) {
	response, err := c.WithRawResponse.GetTransactionEvents(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateConsumerUsers(
	ctx context.Context,
	request *flagrightgo.UserBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.CreateConsumerUsers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetConsumerUsers(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetConsumerUsersRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchConsumerUsersWithRulesResult, error) {
	response, err := c.WithRawResponse.GetConsumerUsers(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateBusinessUsers(
	ctx context.Context,
	request *flagrightgo.BusinessBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.CreateBusinessUsers(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetBusinessUsers(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetBusinessUsersRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchBusinessUsersWithRulesResults, error) {
	response, err := c.WithRawResponse.GetBusinessUsers(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateConsumerUserEvents(
	ctx context.Context,
	request *flagrightgo.ConsumerUserEventBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.CreateConsumerUserEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetConsumerUserEvents(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetConsumerUserEventsRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchConsumerUserEventsRulesResult, error) {
	response, err := c.WithRawResponse.GetConsumerUserEvents(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) CreateBusinessUserEvents(
	ctx context.Context,
	request *flagrightgo.BusinessUserEventBatchRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchResponse, error) {
	response, err := c.WithRawResponse.CreateBusinessUserEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetBusinessUserEvents(
	ctx context.Context,
	// Unique Batch Identifier
	batchId string,
	request *flagrightgo.BatchGetBusinessUserEventsRequest,
	opts ...option.RequestOption,
) (*flagrightgo.BatchBusinessUserEventsWithRulesResult, error) {
	response, err := c.WithRawResponse.GetBusinessUserEvents(
		ctx,
		batchId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
