// Code generated by Fern. DO NOT EDIT.

package business_user_events_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	flagrightgo "github.com/flagright/flagright-go"
	client "github.com/flagright/flagright-go/client"
	option "github.com/flagright/flagright-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBusinessUserEventsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	request := &flagrightgo.BusinessUserEventsCreateRequest{
		AllowUserTypeConversion: flagrightgo.BooleanStringTrue.Ptr(),
		LockKycRiskLevel:        flagrightgo.BooleanStringTrue.Ptr(),
		LockCraRiskLevel:        flagrightgo.BooleanStringTrue.Ptr(),
		Body: &flagrightgo.BusinessUserEvent{
			Timestamp: 1.1,
			UserId:    "userId",
		},
	}
	_, invocationErr := client.BusinessUserEvents.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBusinessUserEventsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBusinessUserEventsCreateWithWireMock", "POST", "/events/business/user", map[string]interface{}{"allowUserTypeConversion": "true", "lockKycRiskLevel": "true", "lockCraRiskLevel": "true"}, 1)
}

func TestBusinessUserEventsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	_, invocationErr := client.BusinessUserEvents.Get(
		context.TODO(),
		"eventId",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBusinessUserEventsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBusinessUserEventsGetWithWireMock", "GET", "/events/business/user/eventId", nil, 1)
}
