// Code generated by Fern. DO NOT EDIT.

package consumer_users_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	flagrightgo "github.com/flagright/flagright-go"
	client "github.com/flagright/flagright-go/client"
	option "github.com/flagright/flagright-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestConsumerUsersCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	request := &flagrightgo.ConsumerUsersCreateRequest{
		LockCraRiskLevel: flagrightgo.BooleanStringTrue.Ptr(),
		LockKycRiskLevel: flagrightgo.BooleanStringTrue.Ptr(),
		ValidateUserId:   flagrightgo.BooleanStringTrue.Ptr(),
		Body: &flagrightgo.User{
			UserId:           "96647cfd9e8fe66ee0f3362e011e34e8",
			CreatedTimestamp: 1641654664000,
			UserDetails: &flagrightgo.UserDetails{
				Name: &flagrightgo.ConsumerName{
					FirstName: "Baran",
					MiddleName: flagrightgo.String(
						"Realblood",
					),
					LastName: flagrightgo.String(
						"Ozkan",
					),
				},
				DateOfBirth: flagrightgo.String(
					"1991-01-01",
				),
				CountryOfResidence:   flagrightgo.CountryCodeUs.Ptr(),
				CountryOfNationality: flagrightgo.CountryCodeDe.Ptr(),
			},
			LegalDocuments: []*flagrightgo.LegalDocument{
				&flagrightgo.LegalDocument{
					DocumentType:   "passport",
					DocumentNumber: "Z9431P",
					DocumentIssuedDate: flagrightgo.Float64(
						1639939034000,
					),
					DocumentExpirationDate: flagrightgo.Float64(
						1839939034000,
					),
					DocumentIssuedCountry: flagrightgo.CountryCodeDe.Ptr(),
					Tags: []*flagrightgo.Tag{
						&flagrightgo.Tag{
							Key:   "customerType",
							Value: "wallet",
						},
					},
				},
			},
			ContactDetails: &flagrightgo.ContactDetails{
				EmailIds: []string{
					"baran@flagright.com",
				},
				ContactNumbers: []string{
					"+37112345432",
				},
				Websites: []string{
					"flagright.com",
				},
				Addresses: []*flagrightgo.Address{
					&flagrightgo.Address{
						AddressLines: []string{
							"Klara-Franke Str 20",
						},
						Postcode: flagrightgo.String(
							"10557",
						),
						City: flagrightgo.String(
							"Berlin",
						),
						State: flagrightgo.String(
							"Berlin",
						),
						Country: flagrightgo.String(
							"Germany",
						),
						Tags: []*flagrightgo.Tag{
							&flagrightgo.Tag{
								Key:   "customKey",
								Value: "customValue",
							},
						},
					},
				},
			},
			Tags: []*flagrightgo.UserTag{
				&flagrightgo.UserTag{
					Key:   "customKey",
					Value: "customValue",
				},
			},
		},
	}
	_, invocationErr := client.ConsumerUsers.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConsumerUsersCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConsumerUsersCreateWithWireMock", "POST", "/consumer/users", map[string]interface{}{"lockCraRiskLevel": "true", "lockKycRiskLevel": "true", "validateUserId": "true"}, 1)
}

func TestConsumerUsersGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	_, invocationErr := client.ConsumerUsers.Get(
		context.TODO(),
		"userId",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConsumerUsersGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConsumerUsersGetWithWireMock", "GET", "/consumer/users/userId", nil, 1)
}
