name: ci

on: [push]

jobs:
 compile:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Set up go
     uses: actions/setup-go@v4

   - name: Install dependency
     run: go mod tidy

   - name: Build
     run: go build ./...

 test:
  needs: [compile]
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Set up go
     uses: actions/setup-go@v4

   - name: Install dependency
     run: go mod tidy

   - name: Run Tests
     run: go test ./...

 publish:
  needs: [compile, test]
  if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repo
     uses: actions/checkout@v3

   - name: Set up Go
     uses: actions/setup-go@v4
     with:
      go-version: '1.24'

   - name: Create GitHub Release
     uses: softprops/action-gh-release@v1
     with:
      tag_name: ${{ github.ref_name }}
      name: Release ${{ github.ref_name }}
      generate_release_notes: true
